[package]
name = "platonic_solids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vera-core = { path = "../../../vera-core" }
vera = { path = "../../../vera" }
fastrand = "2.0.1"