[workspace]
members = [
    "vera",
    "vera-shapes",
    "examples/main/*",
]
resolver = "2"

[workspace.dependencies.vera]
version = "0.2.0"
path = "vera"

[workspace.dependencies.vera-shapes]
version = "0.2.0"
path = "vera-shapes"


[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3