[workspace]
members = [
    "examples/*",
    "vera",
    "vera-shapes",
]
resolver = "2"

[workspace.dependencies.vera]
version = "0.2.0"
path = "vera"

[workspace.dependencies.vera-shapes]
version = "0.2.0"
path = "vera-shapes"
