[workspace]
members = [
    "vera",
    "vera-core",
    "examples/main/*",
]
resolver = "2"

[workspace.dependencies.vera-core]
version = "0.2.0"
path = "vera-core"

[workspace.dependencies.vera]
version = "0.3.0"
path = "vera"


[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3